# Generated by Django 4.2.7 on 2023-11-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_runstring_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runstring',
            name='title2',
        ),
    ]
