# Generated by Django 4.2.7 on 2023-11-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_filmpostmodel_alter_runstring_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_film', models.CharField(max_length=100)),
                ('time_title', models.TimeField()),
                ('hall', models.CharField(max_length=10)),
            ],
        ),
    ]
